export const PakistanCitiesConstants = [
  { cityName: 'Abbottabad', province: 'Khyber Pakhtunkhwa' },
  { cityName: 'Ahmedpur East', province: 'Punjab' },
  { cityName: 'Attock', province: 'Punjab' },
  { cityName: 'Bahawalpur', province: 'Punjab' },
  { cityName: 'Bannu', province: 'Khyber Pakhtunkhwa' },
  { cityName: 'Batkhela', province: 'Khyber Pakhtunkhwa' },
  { cityName: 'Bhakkar', province: 'Punjab' },
  { cityName: 'Chiniot', province: 'Punjab' },
  { cityName: 'Chakwal', province: 'Punjab' },
  { cityName: 'Chaman', province: 'Balochistan' },
  { cityName: 'Dera Ghazi Khan', province: 'Punjab' },
  { cityName: 'Dera Ismail Khan', province: 'Khyber Pakhtunkhwa' },
  { cityName: 'Faisalabad', province: 'Punjab' },
  { cityName: 'Ghotki', province: 'Sindh' },
  { cityName: 'Gujranwala', province: 'Punjab' },
  { cityName: 'Gujrat', province: 'Punjab' },
  { cityName: 'Hyderabad', province: 'Sindh' },
  { cityName: 'Islamabad', province: 'Islamabad Capital Territory' },
  { cityName: 'Jacobabad', province: 'Sindh' },
  { cityName: 'Jhelum', province: 'Punjab' },
  { cityName: 'Karachi', province: 'Sindh' },
  { cityName: 'Kasur', province: 'Punjab' },
  { cityName: 'Kohat', province: 'Khyber Pakhtunkhwa' },
  { cityName: 'Lahore', province: 'Punjab' },
  { cityName: 'Larkana', province: 'Sindh' },
  { cityName: 'Mardan', province: 'Khyber Pakhtunkhwa' },
  { cityName: 'Mirpur', province: 'Azad Jammu & Kashmir' },
  { cityName: 'Multan', province: 'Punjab' },
  { cityName: 'Muzaffarabad', province: 'Azad Jammu & Kashmir' },
  { cityName: 'Nawabshah', province: 'Sindh' },
  { cityName: 'Okara', province: 'Punjab' },
  { cityName: 'Peshawar', province: 'Khyber Pakhtunkhwa' },
  { cityName: 'Quetta', province: 'Balochistan' },
  { cityName: 'Rawalpindi', province: 'Punjab' },
  { cityName: 'Sahiwal', province: 'Punjab' },
  { cityName: 'Sargodha', province: 'Punjab' },
  { cityName: 'Sialkot', province: 'Punjab' },
  { cityName: 'Swabi', province: 'Khyber Pakhtunkhwa' },
  { cityName: 'Swat', province: 'Khyber Pakhtunkhwa' },
  { cityName: 'Turbat', province: 'Balochistan' },
  { cityName: 'Umarkot', province: 'Sindh' },
  { cityName: 'Zhob', province: 'Balochistan' },
];
