import { Select } from '@models/shared/select.model';

export const SubjectsList: Select[] = [
  { Display: 'ART & Modal Drawing', Value: 'ART & Modal Drawing' },
  { Display: 'Agriculture Science (Tech)', Value: 'Agriculture Science (Tech)' },
  { Display: 'Akhlaqiat (Optional)', Value: 'Akhlaqiat (Optional)' },
  { Display: 'Arabic', Value: 'Arabic' },
  { Display: 'Bio Tech', Value: 'Bio Tech' },
  { Display: 'Biology', Value: 'Biology' },
  { Display: 'Chemistry', Value: 'Chemistry' },
  { Display: 'Chemistry Tech', Value: 'Chemistry Tech' },
  { Display: 'Civics', Value: 'Civics' },
  { Display: 'Communication Skills Tech', Value: 'Communication Skills Tech' },
  { Display: 'Computer Science', Value: 'Computer Science' },
  { Display: 'Computer Tech', Value: 'Computer Tech' },
  { Display: 'Computer and entrepreneur Tech', Value: 'Computer and entrepreneur Tech' },
  { Display: 'Economics', Value: 'Economics' },
  { Display: 'Education (Ilm-ul-Taleem)', Value: 'Education (Ilm-ul-Taleem)' },
  { Display: 'English', Value: 'English' },
  { Display: 'English Book I (Short Stories)', Value: 'English Book I (Short Stories)' },
  { Display: 'English Book III', Value: 'English Book III' },
  { Display: 'Ethics', Value: 'Ethics' },
  { Display: 'Farsi', Value: 'Farsi' },
  { Display: 'Fashion Design Tech', Value: 'Fashion Design Tech' },
  { Display: 'General Science', Value: 'General Science' },
  { Display: 'General Science Tech', Value: 'General Science Tech' },
  { Display: 'Geography', Value: 'Geography' },
  { Display: 'Ghiza aur Ghizayat', Value: 'Ghiza aur Ghizayat' },
  { Display: 'Hadiqat-ul-Adab', Value: 'Hadiqat-ul-Adab' },
  { Display: 'Health & Physical Education', Value: 'Health & Physical Education' },
  { Display: 'Health Sciences Tech', Value: 'Health Sciences Tech' },
  { Display: 'History', Value: 'History' },
  { Display: 'Home Economics', Value: 'Home Economics' },
  { Display: 'ICT Tech', Value: 'ICT Tech' },
  { Display: 'Islamiat', Value: 'Islamiat' },
  { Display: 'Itlaqi Barqiat', Value: 'Itlaqi Barqiat' },
  { Display: 'Mantaq', Value: 'Mantaq' },
  { Display: 'Masharti Aloom', Value: 'Masharti Aloom' },
  { Display: 'Mathematics', Value: 'Mathematics' },
  { Display: 'Mr. Chips', Value: 'Mr. Chips' },
  { Display: 'Mubadiyat Falsfa', Value: 'Mubadiyat Falsfa' },
  { Display: 'Muraqa-e-adab', Value: 'Muraqa-e-adab' },
  { Display: 'Nazra Quran', Value: 'Nazra Quran' },
  { Display: 'Neela Qaida (Optional)', Value: 'Neela Qaida (Optional)' },
  { Display: 'Pakistan Studies', Value: 'Pakistan Studies' },
  { Display: 'Parcha Bafi (Textile and Clothing)', Value: 'Parcha Bafi (Textile and Clothing)' },
  { Display: 'Physics', Value: 'Physics' },
  { Display: 'Physics Tech', Value: 'Physics Tech' },
  { Display: 'Primer English', Value: 'Primer English' },
  { Display: 'Primer Mathematics', Value: 'Primer Mathematics' },
  { Display: 'Primer Urdu', Value: 'Primer Urdu' },
  { Display: 'Psychology (Nafsiyat)', Value: 'Psychology (Nafsiyat)' },
  { Display: 'Punjabi', Value: 'Punjabi' },
  { Display: 'Statistics', Value: 'Statistics' },
  { Display: 'TAJVEEDI QAIDA', Value: 'TAJVEEDI QAIDA' },
  { Display: 'TARJUMA-TUL-QURAN-UL MAJEED', Value: 'TARJUMA-TUL-QURAN-UL MAJEED' },
  { Display: 'Urdu', Value: 'Urdu' },
  { Display: 'Waqfiyat e Aama', Value: 'Waqfiyat e Aama' },
  { Display: 'Zari Taleem', Value: 'Zari Taleem' }
];